name: Sync Front End
on: 
  push:
    branches:
      - master

jobs:
  update-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9' 
          architecture: 'x64' 
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./ s3://${{secrets.AWS_S3_BUCKET_NAME }} --delete

# Run Unit tests- Specify unit tests here 

# sam deploy
     